Repository FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec, pull requests merged in 2024-10, with the labels that each got.

#543 Cleanup Metadata PR to fix content bugs/errors, broken links, reduce nesting, formatting
  specification/Makefile
  specification/appendix/commitment_discounts.md
  specification/appendix/examples/examples.mdpp
  specification/appendix/examples/metadata/data_generator_example.md
  specification/appendix/examples/metadata/metadata_examples.mdpp
  specification/appendix/examples/metadata_examples/adding_new_columns_example.md
  specification/appendix/examples/metadata_examples/changing_column_metadata_example.md
  specification/appendix/examples/metadata_examples/correcting_schema_errors_example.md
  specification/appendix/examples/metadata_examples/data_generator_example.md
  specification/appendix/examples/metadata_examples/focus_version_changed_example.md
  specification/appendix/examples/metadata_examples/focus_version_changed_with_provider_version_used_example.md
  specification/appendix/examples/metadata_examples/metadata_examples.mdpp
  specification/appendix/examples/metadata_examples/provider_version_changed_example.md
  specification/appendix/examples/metadata_examples/removing_columns_example.md
  specification/appendix/examples/metadata_examples/schema_metadata_example.md
  specification/appendix/examples/metadata_examples/schema_metadata_reference_example.md
  specification/metadata/data_generator/data_generator.mdpp
  specification/metadata/schema/schema.mdpp
Labels: consistency/review

#549 FOCUS #547: Consistency Review - Standardize column specs for correction charges
  specification/columns/consumedquantity.md
  specification/columns/consumedunit.md
Labels: consistency/review

#552 Service Subcategory language inconsistency fixes
  specification/columns/servicesubcategory.md
Labels: consistency/review

#579 [EDITORIAL - Alternate version] Mark commitment discount purchase's pricing_category as "Standard"
  specification/appendix/commitment_discounts.md
  specification/columns/pricingcategory.md
Labels: consistency/review, editorial

#577 Adding 'Commitment Discount Visibility' to v1.1 Release Planning
  RELEASE-PLANNING.md
Labels: consistency/review

#550 Commitment Discount {Quantity,Unit} - Consistency review edits
  specification/columns/commitmentdiscountquantity.md
  specification/columns/commitmentdiscountunit.md
Labels: consistency/review

#583 [EDITORIAL] Update the list of FOCUS release v1.1 contributors
  specification/contributors.md
Labels: consistency/review, editorial

#581 FOCUS-580: remove use case library and link to the FOCUS website
  specification/use_case_library.md
Labels: consistency/review

#559 Adding Usability Constraints for Aggregation
  specification/columns/commitmentdiscountquantity.md
  specification/columns/contractedcost.md
  specification/columns/contractedunitprice.md
  specification/columns/listcost.md
  specification/columns/listunitprice.md
  specification/columns/pricingquantity.md
Labels: consistency/review

#588 Editorial changes to columns names and ids
  specification/columns/skupricedetails.md
  specification/columns/skupriceid.md
Labels: consistency/review, editorial

#589 Editorial changes to columns names and ids (part 2)
  specification/columns/commitmentdiscountquantity.md
  specification/columns/commitmentdiscountunit.md
  specification/columns/pricingunit.md
  specification/columns/servicesubcategory.md
Labels: consistency/review, editorial

#590 Editorial changes to appendix - links to columns and glossary terms
  specification/appendix/commitment_discounts.md
  specification/appendix/grouping_constructs_for_resources_and_or_services.md
  specification/appendix/origination_of_cost_data.md
Labels: consistency/review, editorial

#591 Editorial changes to columns and glossary terms ordering
  specification/columns/columns.mdpp
  specification/glossary.md
Labels: consistency/review, editorial

#593 Editorial changes: using attribute IDs when referencing attributes in normative paragraphs
  specification/columns/billedcost.md
  specification/columns/billingcurrency.md
  specification/columns/billingperiodend.md
  specification/columns/billingperiodstart.md
  specification/columns/consumedquantity.md
  specification/columns/contractedcost.md
  specification/columns/contractedunitprice.md
  specification/columns/effectivecost.md
  specification/columns/listcost.md
  specification/columns/listunitprice.md
  specification/columns/pricingquantity.md
  specification/columns/tags.md
  specification/metadata/schema/creationdate.md
Labels: consistency/review, editorial

#584 [EDITORIAL] Add Release v1.2 timeline
  RELEASE-PLANNING.md
Labels: repo maintenance

#553 Update feedback use case
  .github/ISSUE_TEMPLATE/feedback.yml
Labels: repo maintenance

#587 New GitHub Issue template for Work Item Creation
  .github/ISSUE_TEMPLATE/work-item.md
  .github/ISSUE_TEMPLATE/work-item.yml
Labels: repo maintenance

#582 Editorial updates on column IDs and Display Names
  EDITORIAL_GUIDELINES.md
Labels: repo maintenance, editorial

#561 Editorial updates to availability zone
  specification/columns/availabilityzone.md
Labels: consistency/review, editorial

#562 Editorial update to billedcost
  specification/columns/billedcost.md
Labels: consistency/review, editorial

#563 Editorial update to billingaccountid
  specification/columns/billingaccountid.md
Labels: consistency/review, editorial

#564 Editorial update to billingaccountname
  specification/columns/billingaccountname.md
Labels: consistency/review, editorial

#565 Editorial update billingcurrency
  specification/columns/billingcurrency.md
Labels: consistency/review, editorial

#567 Editorial updates BillingPeriodStart
  specification/columns/billingperiodstart.md
Labels: consistency/review, editorial

#569 Editorial changes to ChargeFrequency
  specification/columns/chargefrequency.md
Labels: consistency/review, editorial

#570 Editorial update to ChargePeriodEnd
  specification/columns/chargeperiodend.md
Labels: consistency/review, editorial

#571 Editorial updates to ChargePeriodStart
  specification/columns/chargeperiodstart.md
Labels: consistency/review, editorial

#572 Editorial updates to Commitmentdiscountcategory
  specification/columns/commitmentdiscountcategory.md
Labels: consistency/review, editorial

#573 Editorial udpates to CommitmentDiscountId
  specification/columns/commitmentdiscountid.md
Labels: consistency/review, editorial

#574 Editorial update to CommitmentDiscountName
  specification/columns/commitmentdiscountname.md
Labels: consistency/review, editorial

#575 Editorial updates to CommitmentDiscountStatus
  specification/columns/commitmentdiscountstatus.md
Labels: consistency/review, editorial

#576 Editorial updates to CommitmentDiscountType
  specification/columns/commitmentdiscounttype.md
Labels: consistency/review, editorial
