Repository FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec, pull requests merged in 2024-08, with the labels that each got.

#474 FOCUS dataset consistency review
  CHANGELOG.md
  specification/attributes/attributes.mdpp
  specification/attributes/column_naming_and_ordering.md
  specification/attributes/currency_code_format.md
  specification/attributes/datetime_format.md
  specification/attributes/discount_handling.md
  specification/attributes/key_value_format.md
  specification/attributes/numeric_format.md
  specification/attributes/string_handling.md
  specification/attributes/unit_format.md
  specification/columns/availabilityzone.md
  specification/columns/billedcost.md
  specification/columns/billingaccountid.md
  specification/columns/billingaccountname.md
  specification/columns/billingcurrency.md
  specification/columns/billingperiodend.md
  specification/columns/billingperiodstart.md
  specification/columns/chargecategory.md
  specification/columns/chargeclass.md
  specification/columns/chargedescription.md
  specification/columns/chargefrequency.md
  specification/columns/chargeperiodend.md
  specification/columns/chargeperiodstart.md
  specification/columns/commitmentdiscountcategory.md
  specification/columns/commitmentdiscountid.md
  specification/columns/commitmentdiscountname.md
  specification/columns/commitmentdiscountstatus.md
  specification/columns/commitmentdiscounttype.md
  specification/columns/consumedquantity.md
  specification/columns/consumedunit.md
  specification/columns/contractedcost.md
  specification/columns/contractedunitprice.md
  specification/columns/effectivecost.md
  specification/columns/invoiceissuer.md
  specification/columns/listcost.md
  specification/columns/listunitprice.md
  specification/columns/pricingcategory.md
  specification/columns/pricingquantity.md
  specification/columns/pricingunit.md
  specification/columns/provider.md
  specification/columns/publisher.md
  specification/columns/regionid.md
  specification/columns/regionname.md
  specification/columns/resourceid.md
  specification/columns/resourcename.md
  specification/columns/resourcetype.md
  specification/columns/servicecategory.md
  specification/columns/servicename.md
  specification/columns/skuid.md
  specification/columns/skupriceid.md
  specification/columns/subaccountid.md
  specification/columns/subaccountname.md
  specification/columns/tags.md
  specification/glossary.md
Labels: P1, editorial

#505 FOCUS #491: ChargeClass - 'Corrections' as a result of late arriving charge records
  specification/columns/chargeclass.md
  supporting_content/columns/chargeclass.md
Labels: P1

#527 Remove incorrect mention of 'Charge Subcategory' and correct with 'Charge Category'
  specification/attributes/discount_handling.md
Labels: P1, bug in version

#524 Rename all mentions on "commitment-based discount" (or similar) to "commitment discount" (or similar) to match updated iteration of term in FinOps Terminology page.
  specification/attributes/discount_handling.md
  specification/columns/commitmentdiscountcategory.md
  specification/columns/commitmentdiscountid.md
  specification/columns/commitmentdiscountname.md
  specification/columns/commitmentdiscountstatus.md
  specification/columns/commitmentdiscounttype.md
  specification/columns/contractedcost.md
  specification/columns/contractedunitprice.md
  specification/columns/effectivecost.md
  specification/columns/listcost.md
  specification/columns/pricingcategory.md
  specification/glossary.md
  specification/use_case_library.md
  supporting_content/attributes/discount_handling.md
  supporting_content/columns/chargecategory.md
  supporting_content/columns/contractedunitprice.md
  supporting_content/columns/listunitprice.md
  supporting_content/columns/pricingcategory.md
  supporting_content/columns/pricingquantity.md
Labels: P1
