Repository FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec, pull requests merged in 2024-06, with the labels that each got.

#478 Update scope and interim consistency review milestones, and scope top…
  RELEASE-PLANNING.md
Labels: repo maintenance

#484 [ADMIN] [EDITORIAL] Editorial changes to 1.0-cr
  CHANGELOG.md
  license.md
  specification/columns/billingperiodend.md
  specification/columns/chargecategory.md
  specification/columns/columns.mdpp
  specification/columns/consumedunit.md
  specification/glossary.md
Labels: editorial

#480 [ADMIN]update reference to patent policy 4 W3C mode as stated in the FOCUS Membership doc.
  license.md
Labels: repo maintenance, editorial

#483 [EDITORIAL] Update billingperiodend.md
  specification/columns/billingperiodend.md
Labels: bug in version, editorial
