Repository FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec, pull requests merged in 2024-05, with the labels that each got.

#428 424: Description updates on when to exclude to avoid double counting List/Contracted
  specification/columns/contractedcost.md
  specification/columns/listcost.md
  supporting_content/columns/contractedcost.md
  supporting_content/columns/listcost.md
Labels: Consistency/Review

#433 426-consistency-review-chargecategory-definition-and-description-review
  specification/columns/chargecategory.md
Labels: Consistency/Review

#431 FOCUS #430: EffectiveCost spec change - addressing purchases paid to cover future eligible charges
  CHANGELOG.md
  specification/columns/effectivecost.md
  specification/glossary.md
Labels: Consistency/Review

#450 Rename branch candidate_release to candidate_recommendation
  .github/workflows/candidate_release.yml
Labels: repo maintenance

#418 #409 Path 1 - Usage Unit/Quantity restricted to usage charges and renamed to Consumed Unit/Quantity
  CHANGELOG.md
  specification/columns/columns.mdpp
  specification/columns/consumedquantity.md
  specification/columns/consumedunit.md
  specification/columns/pricingquantity.md
  specification/columns/pricingunit.md
  specification/columns/usagequantity.md
  specification/columns/usageunit.md
  specification/glossary.md
  supporting_content/columns/consumedquantity.md
  supporting_content/columns/consumedunit.md
  supporting_content/columns/usagequantity.md
Labels: Consistency/Review

#443 #436 Add helpful text for identifying records that need to be burned-down
  specification/columns/contractedcost.md
  specification/columns/listcost.md
Labels: Consistency/Review

#444 #441 Clarifications for various Commitment discount scenarios
  specification/attributes/discount_handling.md
  specification/columns/commitmentdiscountstatus.md
Labels: Consistency/Review

#442 #441 ChargePeriod Start and End spec change
  specification/columns/chargeperiodend.md
  specification/columns/chargeperiodstart.md
  specification/glossary.md
Labels: Consistency/Review

#453 [ADMIN] Add steering, contributors and maintainers who contributed to FOCUS
  specification/contributors.md
Labels: Consistency/Review

#432 FOCUS #425: ChargeClass (Path 1) - spec updates and associated columns adjustments
  CHANGELOG.md
  specification/columns/chargeclass.md
  specification/columns/contractedunitprice.md
  specification/columns/listunitprice.md
  specification/columns/pricingcategory.md
  specification/columns/skuid.md
  specification/columns/skupriceid.md
  supporting_content/columns/chargeclass.md
  supporting_content/columns/skupriceid.md
Labels: Consistency/Review

#429 Update contributors.md
  specification/contributors.md
Labels: Consistency/Review

#454 Update Use Case examples with new column names #452
  specification/use_case_library.md
Labels: Consistency/Review

#455 [EDITORIAL] Update changelog
  CHANGELOG.md
Labels: repo maintenance

#459 [EDITORIAL] v1.0 Correct typo in consumedunit.md
  specification/columns/consumedunit.md
Labels: Consistency/Review, bug in version

#460 [EDITORIAL] Update columns.mdpp
  specification/columns/columns.mdpp
Labels: Consistency/Review, bug in version

#461 [EDITORIAL] Correct a typographical error in the ChargeCategory.
  specification/columns/chargecategory.md
Labels: Consistency/Review, bug in version

#463 [PROCESS] update release planning content
  RELEASE-PLANNING.md
Labels: repo maintenance

#470 Fix changelog commit history link
  CHANGELOG.md
Labels: repo maintenance, bug in version, editorial

#468 [ADMIN] remove specific dates for 2025 releases
  RELEASE-PLANNING.md
Labels: repo maintenance, editorial
