Repository FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec, pull requests merged in 2024-09, with the labels that each got.

#501 [ADMIN] Add editorial guidelines document
  EDITORIAL_GUIDELINES.md
Labels: repo maintenance

#530 #503a - Update SkuPriceId per SkuPriceDetails
  specification/columns/skupriceid.md
Labels: P1

#523 Capacity Reservation Proposal for ID & Status
  specification/columns/capacityreservationid.md
  specification/columns/capacityreservationstatus.md
  specification/glossary.md
Labels: P1

#503 FOCUS #497: SkuPriceDetails column
  specification/attributes/column_naming_and_ordering.md
  specification/columns/columns.mdpp
  specification/columns/skupricedetails.md
  specification/glossary.md
Labels: P1

#538 Fix CDStatus column reference
  specification/columns/commitmentdiscountstatus.md
Labels: breaking change 🚨, P1, bug in version

#533 FOCUS #532: PricingCategory update - Classify commitment discount purchase records as Standard instead of Committed
  specification/columns/pricingcategory.md
Labels: breaking change 🚨, P1, bug in version

#541 Add 1 missing space between "commitment discount" and "identified"
  specification/columns/commitmentdiscountcategory.md
Labels: editorial

#514 Improvements To Metadata
  specification/appendix/appendix.mdpp
  specification/appendix/examples/examples.mdpp
  specification/appendix/examples/metadata/adding_new_columns_example.md
  specification/appendix/examples/metadata/changing_column_metadata_example.md
  specification/appendix/examples/metadata/correcting_schema_errors_example.md
  specification/appendix/examples/metadata/data_generator_example.md
  specification/appendix/examples/metadata/focus_version_changed_example.md
  specification/appendix/examples/metadata/focus_version_changed_with_provider_version_used_example.md
  specification/appendix/examples/metadata/metadata_examples.mdpp
  specification/appendix/examples/metadata/provider_version_changed_example.md
  specification/appendix/examples/metadata/removing_columns_example.md
  specification/appendix/examples/metadata/schema_metadata_example.md
  specification/appendix/examples/metadata/schema_metadata_reference_example.md
  specification/metadata/data_generator/data_generator.mdpp
  specification/metadata/data_generator/datagenerator.md
  specification/metadata/metadata.mdpp
  specification/metadata/schema/column_definition/column_definition.mdpp
  specification/metadata/schema/column_definition/columnname.md
  specification/metadata/schema/column_definition/datatype.md
  specification/metadata/schema/column_definition/numberscale.md
  specification/metadata/schema/column_definition/numericprecision.md
  specification/metadata/schema/column_definition/providertagprefixes.md
  specification/metadata/schema/column_definition/stringencoding.md
  specification/metadata/schema/column_definition/stringmaxlength.md
  specification/metadata/schema/creationdate.md
  specification/metadata/schema/focusversion.md
  specification/metadata/schema/providerversion.md
  specification/metadata/schema/schema.mdpp
  specification/metadata/schema/schemaid.md
  supporting_content/metadata/schema_creation_scenarios.md
Labels: P1

#519 FOCUS #404: Service Subcategory
  specification/columns/columns.mdpp
  specification/columns/servicesubcategory.md
  supporting_content/columns/servicesubcategory.md
Labels: P1

#516 Dedicated SKU column (for issue #495)
  specification/columns/columns.mdpp
  specification/columns/skumeter.md
  supporting_content/columns/skumeter.md
Labels: P1

#528 Commitment Discount Appendix
  specification/appendix/appendix.mdpp
  specification/appendix/commitment_discounts.md
  specification/glossary.md
  specification/markdownlnt.cfg
Labels: P2

#544 [EDITORIAL] Fix single-word glossary term italics
  specification/appendix/commitment_discounts.md
Labels: Consistency/Review

#545 [Editorial] Normalize all instances of commitment discount flexibility as "commitment discount flexibility"
  specification/appendix/commitment_discounts.md
  specification/columns/commitmentdiscountquantity.md
  specification/columns/commitmentdiscountunit.md
  specification/columns/skupriceid.md
  specification/glossary.md
  supporting_content/columns/effectivecost.md
Labels: Consistency/Review

#548 FOCUS 1.1 changelog updates
  CHANGELOG.md
Labels: Consistency/Review

#558 Repaired the table format in supporting content for SubaccountID
  supporting_content/columns/subaccountid.md
Labels: Consistency/Review
