Repository FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec, pull requests merged in 2024-07, with the labels that each got.

#471 Update glossary - remove duplicate entry
  specification/glossary.md
Labels: editorial

#481 Rename CommitmentDiscountStatus supporting content file
  supporting_content/columns/commitmentdiscountstatus.md
Labels: editorial

#490 [REPO] Enhance Issue Templates
  .github/ISSUE_TEMPLATE/discussion-topic.yml
  .github/ISSUE_TEMPLATE/feedback.yml
  .github/ISSUE_TEMPLATE/maintenance.yml
  .github/ISSUE_TEMPLATE/spec-change.md
  .github/ISSUE_TEMPLATE/spec_change.yml
Labels: repo maintenance

#506 [EDITORIAL] Reclassify ConsumedUnit as Dimension instead of Metric
  specification/columns/consumedunit.md
Labels: P1, bug in version, editorial

#504 Proposal for FOCUS v1.1 Scope
  RELEASE-PLANNING.md
Labels: P1
