Repository FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec, pull requests merged in 2025-03, with the labels that each got.

#811 [ADMIN] add invoiceid to columns file
  specification/columns/columns.mdpp
  specification/columns/invoiceid.md
Labels: editorial

#821 [Maintenance] Updated GitHub actions to use Ubuntu 24.04 due to deprecation notice.
  .github/workflows/candidate_release.yml
  .github/workflows/main.yml
  .github/workflows/working_draft.yml
Labels: repo maintenance

#812 WI #643: Add supported feature for service categorization
  specification/supported_features/service_categorization.md
  specification/supported_features/supported_features.mdpp
Labels: 1.2

#809 WI #643: Add supported feature for resource usage
  specification/supported_features/resource_usage.md
  specification/supported_features/supported_features.mdpp
Labels: 1.2

#677 WI #678: Adding use case to work item template
  .github/ISSUE_TEMPLATE/feedback.md
  .github/ISSUE_TEMPLATE/feedback.yml
  .github/ISSUE_TEMPLATE/work-item.md
  .github/ISSUE_TEMPLATE/work-item.yml
  supporting_content/usecases/howtocraftusecases.md
Labels: 1.2

#828 WI #615: Update `Invoice ID` with credit handling requirements
  specification/columns/invoiceid.md
  supporting_content/columns/invoiceid.md
Labels: spec revision

#844 WI #643: SemVer Usage clarification from Maintainers Aug 19 2024 meeting in the spec
  CHANGELOG.md
  README.md
  specification/columns/invoiceid.md
Labels: spec revision

#535 WI #634: Commitment Discount Flexibility Appendix
  specification/appendix/appendix.mdpp
  specification/appendix/commitment_discounts/commitment_discounts.md
  specification/appendix/commitment_discounts/commitment_discounts.mdpp
  specification/appendix/examples/commitment_discount_flexibility_examples/commitment_discount_flexibility_examples.mdpp
  specification/appendix/examples/commitment_discount_flexibility_examples/one_hundred_percent_utilization_with_commitment_discount_flexibility_with_1_resource.md
  specification/appendix/examples/commitment_discount_flexibility_examples/one_hundred_percent_utilization_with_commitment_discount_flexibility_with_2_resources.md
  specification/appendix/examples/commitment_discount_flexibility_examples/one_hundred_percent_utilization_without_commitment_discount_flexibility.md
  specification/appendix/examples/commitment_discount_flexibility_examples/zero_percent_utilization_without_commitment_discount_flexibility.md
  specification/appendix/examples/examples.mdpp
  specification/columns/commitmentdiscountquantity.md
  specification/columns/commitmentdiscountunit.md
  specification/columns/skupriceid.md
Labels: spec revision, 1.2

#830 WI #616: Initial Example Section - cleaned up data and spec content
  specification/Makefile
  specification/appendix/appendix.mdpp
  specification/appendix/metadata_examples/adding_new_columns_example.md
  specification/appendix/metadata_examples/changing_column_metadata_example.md
  specification/appendix/metadata_examples/correcting_schema_errors_example.md
  specification/appendix/metadata_examples/data_generator_example.md
  specification/appendix/metadata_examples/focus_version_changed_example.md
  specification/appendix/metadata_examples/focus_version_changed_with_provider_version_used_example.md
  specification/appendix/metadata_examples/metadata_examples.mdpp
  specification/appendix/metadata_examples/provider_version_changed_example.md
  specification/appendix/metadata_examples/removing_columns_example.md
  specification/appendix/metadata_examples/schema_metadata_example.md
  specification/appendix/metadata_examples/schema_metadata_reference_example.md
  specification/appendix/saas_examples/saas_examples.mdpp
  specification/appendix/saas_examples/simple_agreements.md
  specification/appendix/saas_examples/spend_agreements.md
  specification/styles/base.css
Labels: spec revision
