Repository FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec, pull requests merged in 2025-04, with the labels that each got.

#859 858 upstream dependancy issues
  .gitignore
  specification/images/88x31.png
  specification/images/License-CC-BY-4.0-lightgrey.svg
  specification/license.md
Labels: repo maintenance, 1.2

#861 Added extra build step for failure
  .github/workflows/candidate_release.yml
  .github/workflows/main.yml
  .github/workflows/working_draft.yml
Labels: repo maintenance, 1.2

#798 WI #557: Normative Requirements Refinement - Part 2
  guidelines/normative_requirements_guidelines.md
  specification/columns/billedcost.md
  specification/columns/billingaccounttype.md
  specification/columns/commitmentdiscountquantity.md
  specification/columns/commitmentdiscountunit.md
  specification/columns/consumedquantity.md
  specification/columns/consumedunit.md
  specification/columns/contractedcost.md
  specification/columns/contractedunitprice.md
  specification/columns/effectivecost.md
  specification/columns/invoiceid.md
  specification/columns/listcost.md
  specification/columns/listunitprice.md
  specification/columns/pricingquantity.md
  specification/columns/pricingunit.md
  specification/columns/skuid.md
  specification/columns/skumeter.md
  specification/columns/skupricedetails.md
  specification/columns/skupriceid.md
  specification/columns/subaccounttype.md
  specification/columns/tags.md
Labels: spec revision

#684 WI #643: Specification Change Guidelines
  CHANGELOG.md
  guidelines/spec-change-guidelines.md
  specification/appendix/metadata_examples/deprecating_columns_example.md
  specification/appendix/metadata_examples/metadata_examples.mdpp
  specification/appendix/metadata_examples/renaming_columns_example.md
  specification/metadata/schema/column_definition/column_definition.mdpp
  specification/metadata/schema/column_definition/deprecated.md
  specification/metadata/schema/column_definition/previouscolumnname.md
Labels: spec revision, 1.2

#786 WI #643: Supported Features In Spec
  specification/Makefile
  specification/spec.mdpp
  specification/supported_features/account_structures.md
  specification/supported_features/billed_cost_and_invoice_alignment.md
  specification/supported_features/charge_categorization.md
  specification/supported_features/commit_usage_and_under_usage.md
  specification/supported_features/cost_and_usage_attribution.md
  specification/supported_features/cost_comparison.md
  specification/supported_features/custom_columns.md
  specification/supported_features/data_granularity.md
  specification/supported_features/effective_cost.md
  specification/supported_features/location.md
  specification/supported_features/marketplace_purchases.md
  specification/supported_features/provider_services.md
  specification/supported_features/resource_usage.md
  specification/supported_features/schema_metadata.md
  specification/supported_features/service_categorization.md
  specification/supported_features/supported_features.mdpp
  specification/supported_features/verify_compare_track_unit_prices.md
Labels: spec revision

#838 WI #617: Proposal for data included in a FOCUS dataset
  CHANGELOG.md
  specification/attributes/attributes.mdpp
  specification/attributes/column_naming_and_ordering.md
  specification/glossary.md
  supporting_content/attributes/column_handling.md
Labels: spec revision

#843 WI #616: Renaming `Provider Version` to `Data Generator Version` in metadata
  specification/appendix/metadata_examples/data_generator_version_changed_example.md
  specification/appendix/metadata_examples/focus_version_changed_with_data_generator_version_used_example.md
  specification/appendix/metadata_examples/focus_version_changed_with_provider_version_used_example.md
  specification/appendix/metadata_examples/metadata_examples.mdpp
  specification/attributes/attributes.mdpp
  specification/attributes/column_naming_and_ordering.md
  specification/metadata/schema/datageneratorversion.md
  specification/metadata/schema/providerversion.md
  specification/metadata/schema/schema.mdpp
Labels: spec revision

#683 WI #619: `SKU Price Details` preferred keys
  CHANGELOG.md
  specification/columns/skupricedetails.md
  supporting_content/columns/skupricedetails.md
Labels: spec revision, 1.2

#676 WI #314: `SKU ID`, `SKU Price ID` and `SKU Price Details` clarification
  specification/columns/skuid.md
  specification/columns/skumeter.md
  specification/columns/skupricedetails.md
  specification/columns/skupriceid.md
  specification/glossary.md
  supporting_content/columns/skuid.md
  supporting_content/columns/skupriceid.md
Labels: spec revision, 1.2

#780 WI #616: Proposed change to billed cost to prevent double counting billed cost…
  specification/columns/billedcost.md
  specification/columns/invoiceissuer.md
Labels: spec revision

#887 Fix issue where the spec.md file is not being found to upload as an a…
  .github/workflows/candidate_release.yml
  .github/workflows/main.yml
  .github/workflows/working_draft.yml
Labels: repo maintenance

#865 AI #864: Strike extra row in Billing Account Type and Sub Account Type
  specification/columns/billingaccounttype.md
  specification/columns/subaccounttype.md
Labels: consistency review, editorial

#871 AI #870: Add 1.2 contributors
  specification/contributors.md
Labels: consistency review

#888 commitmentdiscountstatus.md spelling mistake
  specification/columns/commitmentdiscountstatus.md
Labels: consistency review, editorial

#904 Added new pandoc plugin to rewrite relative links
  .github/workflows/candidate_release.yml
  .github/workflows/main.yml
  .github/workflows/working_draft.yml
  specification/Makefile
  vendored/pandoc-project-relative-links/pandoc-project-relative-links.py
Labels: repo maintenance, 1.2

#907 Reflect the development branch in specification document build for pre-production builds
  specification/Makefile
Labels: repo maintenance

#867 AI #866: Add 1.2 changes to the changelog
  CHANGELOG.md
Labels: consistency review

#869 AI #868: Clean up guidelines formatting
  guidelines/normative-requirements-guidelines.md
  guidelines/spec-development-guidelines.md
Labels: consistency review

#873 WI #854: Remove unnecessary "row" references
  specification/columns/billingaccounttype.md
  specification/columns/subaccounttype.md
Labels: consistency review, 1.2

#878 AI #872: Revised 1. Introduction
  specification/overview.md
Labels: consistency review, editorial

#882 AI #881: Reorganize appendix
  specification/appendix/appendix.mdpp
  specification/appendix/commitment_discounts/commitment_discounts.md
  specification/appendix/examples/commitment_discount_flexibility_examples/commitment_discount_flexibility_examples.mdpp
  specification/appendix/grouping_constructs_for_resources_and_or_services.md
  specification/appendix/metadata_examples/metadata_examples.mdpp
  specification/appendix/saas_examples/saas_examples.mdpp
Labels: consistency review

#890 AI #880: Change open-source to open
  specification/spec.mdpp
Labels: consistency review, editorial

#892 AI #877: Typos and simple grammatical improvements to the spec
  specification/appendix/commitment_discounts/commitment_discounts.md
  specification/appendix/metadata_examples/adding_new_columns_example.md
  specification/appendix/metadata_examples/focus_version_changed_example.md
  specification/appendix/metadata_examples/renaming_columns_example.md
  specification/appendix/metadata_examples/schema_metadata_example.md
  specification/appendix/saas_examples/spend_agreements.md
  specification/columns/commitmentdiscountquantity.md
  specification/columns/effectivecost.md
  specification/columns/listcost.md
  specification/columns/pricingquantity.md
  specification/columns/pricingunit.md
  specification/columns/skuid.md
  specification/columns/skupricedetails.md
  specification/columns/tags.md
  specification/glossary.md
  specification/metadata/schema/column_definition/deprecated.md
  specification/metadata/schema/column_definition/providertagprefixes.md
  specification/supported_features/commit_usage_and_under_usage.md
  specification/supported_features/cost_and_usage_attribution.md
  specification/supported_features/marketplace_purchases.md
  specification/supported_features/verify_compare_track_unit_prices.md
Labels: consistency review, editorial

#893 AI #847: Including the Virtual Currency pricing model example for the SaaS appendix
  specification/appendix/saas_examples/saas_examples.mdpp
  specification/appendix/saas_examples/virtual_currency_pricing_model.md
  specification/data/saas_examples/virtual_currency_pricing_model_a1.csv
  specification/data/saas_examples/virtual_currency_pricing_model_a2.csv
  specification/data/saas_examples/virtual_currency_pricing_model_b1.csv
  specification/data/saas_examples/virtual_currency_pricing_model_b2.csv
  specification/data/saas_examples/virtual_currency_pricing_model_b3.csv
  specification/data/saas_examples/virtual_currency_pricing_model_c.csv
Labels: spec revision

#896 AI #863: Convert appendix examples to CSV: Commitment Discounts
  specification/appendix/commitment_discounts/commitment_discounts.md
  specification/appendix/examples/commitment_discount_flexibility_examples/one_hundred_percent_utilization_with_commitment_discount_flexibility_with_1_resource.md
  specification/appendix/examples/commitment_discount_flexibility_examples/one_hundred_percent_utilization_with_commitment_discount_flexibility_with_2_resources.md
  specification/appendix/examples/commitment_discount_flexibility_examples/one_hundred_percent_utilization_without_commitment_discount_flexibility.md
  specification/appendix/examples/commitment_discount_flexibility_examples/zero_percent_utilization_without_commitment_discount_flexibility.md
  specification/data/commitment_discount_flexibility/one_hundred_percent_utilization_with_commitment_discount_flexibility_with_1_resource.csv
  specification/data/commitment_discount_flexibility/one_hundred_percent_utilization_with_commitment_discount_flexibility_with_2_resources.csv
  specification/data/commitment_discount_flexibility/one_hundred_percent_utilization_without_commitment_discount_flexibility.csv
  specification/data/commitment_discount_flexibility/zero_percent_utilization_without_commitment_discount_flexibility.csv
  specification/data/commitment_discount_scenarios/commitment_discount_purchase_scenario_1.csv
  specification/data/commitment_discount_scenarios/commitment_discount_purchase_scenario_2.csv
  specification/data/commitment_discount_scenarios/commitment_discount_purchase_scenario_3.csv
  specification/data/commitment_discount_scenarios/commitment_discount_usage_scenario_1.csv
  specification/data/commitment_discount_scenarios/commitment_discount_usage_scenario_2.csv
  specification/data/commitment_discount_scenarios/commitment_discount_usage_scenario_3.csv
  specification/data/commitment_discount_scenarios/commitment_discount_usage_scenario_4.csv
Labels: consistency review

#898 AI #870: Revise 1.2 contributors list
  specification/contributors.md
Labels: consistency review

#900 WI #854: Clean up outstanding references to `Provider Version` in examples
  specification/appendix/metadata_examples/data_generator_version_changed_example.md
Labels: consistency review

#901 AI #883: Update section 1.4.4 extensibility
  specification/overview.md
Labels: consistency review

#905 AI #902: Revise and align SKU and SKU Price related columns post-merge
  specification/columns/skupricedetails.md
Labels: consistency review

#908 AI #863: Convert appendix examples to CSV: SaaS
  specification/appendix/saas_examples/simple_agreements.md
  specification/appendix/saas_examples/spend_agreements.md
  specification/data/saas_examples/simple_agreements/simple_saas_agreements_a1.csv
  specification/data/saas_examples/simple_agreements/simple_saas_agreements_a2.csv
  specification/data/saas_examples/simple_agreements/simple_saas_agreements_a3.csv
  specification/data/saas_examples/simple_agreements/simple_saas_agreements_b.csv
  specification/data/saas_examples/simple_agreements/simple_saas_agreements_c.csv
  specification/data/saas_examples/spend_agreements/saas_spend_agreements_a1.csv
  specification/data/saas_examples/spend_agreements/saas_spend_agreements_a2.csv
  specification/data/saas_examples/spend_agreements/saas_spend_agreements_b1.csv
  specification/data/saas_examples/spend_agreements/saas_spend_agreements_b2.csv
Labels: consistency review

#912 AI #874: Alignment with column normative reqs - BilledCost and PricingCurrencyEffectiveCost
  specification/columns/billedcost.md
  specification/columns/pricingcurrencycontractedunitprice.md
  specification/columns/pricingcurrencyeffectivecost.md
  specification/columns/pricingcurrencylistunitprice.md
Labels: consistency review

#914 AI #913: Editorial Adjustments (Best Effort) – Links and Formatting
  specification/columns/availabilityzone.md
  specification/columns/billingcurrency.md
  specification/columns/billingperiodend.md
  specification/columns/billingperiodstart.md
  specification/columns/capacityreservationid.md
  specification/columns/capacityreservationstatus.md
  specification/columns/chargecategory.md
  specification/columns/chargeclass.md
  specification/columns/chargedescription.md
  specification/columns/chargefrequency.md
  specification/columns/chargeperiodend.md
  specification/columns/chargeperiodstart.md
  specification/columns/commitmentdiscountid.md
  specification/columns/commitmentdiscountquantity.md
  specification/columns/commitmentdiscountstatus.md
  specification/columns/contractedcost.md
  specification/columns/effectivecost.md
  specification/columns/invoiceid.md
  specification/columns/listcost.md
  specification/columns/pricingcategory.md
  specification/columns/pricingquantity.md
  specification/columns/resourceid.md
  specification/columns/resourcetype.md
  specification/columns/servicename.md
  specification/columns/skuid.md
  specification/columns/skumeter.md
  specification/columns/subaccountid.md
  specification/columns/tags.md
Labels: consistency review

#915 Fix typo in skupricedetails.md
  supporting_content/columns/skupricedetails.md
Labels: consistency review, editorial

#933 Scrub of Supported Features
  specification/supported_features/account_structures.md
  specification/supported_features/billed_cost_and_invoice_alignment.md
  specification/supported_features/charge_categorization.md
  specification/supported_features/commit_usage_and_under_usage.md
  specification/supported_features/cost_and_usage_attribution.md
  specification/supported_features/cost_comparison.md
  specification/supported_features/custom_columns.md
  specification/supported_features/data_granularity.md
  specification/supported_features/effective_cost.md
  specification/supported_features/location.md
  specification/supported_features/marketplace_purchases.md
  specification/supported_features/provider_services.md
  specification/supported_features/resource_usage.md
  specification/supported_features/schema_metadata.md
  specification/supported_features/service_categorization.md
  specification/supported_features/verify_compare_track_unit_prices.md
Labels: consistency review

#931 Repair column handling references
  specification/attributes/attributes.mdpp
  specification/attributes/column_handling.md
  specification/overview.md
Labels: consistency review

#916 [ADMIN] Update release planning with Release 1.3 details
  RELEASE-PLANNING.md
Labels: editorial, 1.3 consideration, 1.3
