Repository FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec, pull requests merged in 2025-05, with the labels that each got.

#1062 added panflute to requirements to ensure its available to the build p…
  requirements.txt
Labels: repo maintenance

#940 Repair Billing Currency glossary references
  specification/glossary.md
Labels: consistency review, editorial

#953 AI #814: Revised spec development guidelines
  guidelines/development-processes.md
  guidelines/spec-development-guidelines.md
Labels: editorial, supporting content
